version: '3.8'
services:
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: server-backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  client:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: client-frontend
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true